//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Data = new HashSet<Data>();
        }
    
        public int clientId { get; set; }
        public string nameClient { get; set; }
        public Nullable<bool> sexClientId { get; set; }
        public string numberPhoneClient { get; set; }
        public string passportClient { get; set; }
        public string loginClient { get; set; }
        public string passwordClient { get; set; }
        public Nullable<bool> roleClient { get; set; }
        public string imageClient { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Data> Data { get; set; }
    }
}
