//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diplom.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int dataId { get; set; }
        public string name { get; set; }
        public Nullable<int> clientId { get; set; }
        public Nullable<System.DateTime> dateStart { get; set; }
        public Nullable<int> volume { get; set; }
        public string photo { get; set; }
        public string description { get; set; }
        public Nullable<int> statusId { get; set; }
        public Nullable<int> stoPerId { get; set; }
        public Nullable<int> stoSecId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status { get; set; }
        public virtual StoragePeriod StoragePeriod { get; set; }
        public virtual StorageSection StorageSection { get; set; }
    }
}
